[package]
authors = ["Anthony Cramp <anthony.cramp@gmail.com>"]
edition = "2018"
name = "day04"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
test_support = {path = "../test_support"}
